sweagent/environment/swe_env.py, sweagent/environment/utils.py
Currently running with the setup defined in the README the `python run.py ...` will fail at `get_instances` because `GhApi` reads the github token from environment variables.
Setup:
keys.cfg
```
OPENAI_API_TOKEN="xxx"
GITHUB_TOKEN="xxxx"
```
Ensure GITHUB_TOKEN is not exported in environment:
`unset GITHUB_TOKEN`
Command:
```
python run.py --model_name gpt4   --data_path https://github.com/tcoyze/calendly-webhook/issues/1   --config_file config/default_from_url.yaml
```
Example error:
```
...
/home/tyler/miniconda3/envs/swe-agent/lib/python3.9/site-packages/ghapi/core.py:102: UserWarning: Neither GITHUB_TOKEN nor GITHUB_JWT_TOKEN found: running as unauthenticated
else: warn('Neither GITHUB_TOKEN nor GITHUB_JWT_TOKEN found: running as unauthenticated')
Traceback (most recent call last): …
```
=> fix: allow token from keys.cfg to get passed to ghapi

environment.yml, setup.py
requirement is not used anywhere and causes a setup failure on windows as the dependency cannot be used with windows
=> chore: remove gnureadline dependency

README.md
I noticed there is also a `TOGETHER_API_KEY` key that can be set in `keys.cfg` while I was investigating https://github.com/princeton-nlp/SWE-agent/issues/26#issuecomment-2035899278, but it wasn't mentioned in the README, so I wanted to add it:
https://github.com/princeton-nlp/SWE-agent/blob/6c9ebf0ea8a263806b276da7ba3b1eda1f4a9475/sweagent/agent/models.py#L509-L511
I also moved the `GITHUB_TOKEN` to the top of the list, since it's a required token.
=> add TOGETHER_API_KEY to keys.cfg section of README

run.py, run_replay.py, sweagent/agent/agents.py, sweagent/environment/swe_env.py, sweagent/environment/utils.py
Example PR: https://github.com/klieret/swe-agent-test-repo/pull/12
* PR is only created as draft and has to be manually marked as "ready for review"
PRs only get created if
* swe-agent reports success
* issue is open
* no one is assigned to issue
* no commit references the issue as 'closes #xx' (can be overridden)
* issue is not locked
Optional/separate PR:
Closes #8 
Also thanks to @themrzmaster who opened a PR for the same issue in #37.
=> Feat: Open PR to repo

sweagent/environment/utils.py
Not 100% sure how this was used before, but the current code clearly doesn't work, so this can only help. 
Closes #70
=> Fix: Unexpected keyword 'split' in load_dataset

README.md, sweagent/agent/models.py
Adds support for models hosted on Azure OpenAI under the model prefix `azure:`. 
Part of #14 & #22
=> feat: add support for azure openai

config/commands/search.sh
There is a rare issue when the agent searches for search terms starting with dashes, e.g. `search_file "--flag"`. These are interpreted as flags by the underlying grep command, which results in errors ("unrecognized flag") or in the worst case hanging since the search term is missing.
Separating flags from positional arguments with "--" should do the trick.
=> Fix searching for flag-like strings, e.g., search_file "--flag"

Dockerfile
Part of a solution to #66 and might help people running Windows as well.
Current way of running this:
```bash
docker build -t swe-agent-run:latest .  && \
docker run -it -v /var/run/docker.sock:/var/run/docker.sock --rm swe-agent-run:latest  \
python3 run.py --model_name gpt4 \
--data_path  https://github.com/klieret/swe-agent-test-repo/issues/1 \
--config_file config/default_from_url.yaml
```
Closes #28
=> Containerize application

sweagent/environment/swe_env.py
Fixes an issue with windows where `\r\n` is getting sent to the docker image instead of `\n`. This is documented in the [subprocess](https://docs.python.org/3/library/subprocess.html) api as it replaces `\n` with `os.linesep`. With #17, this can be fully run on windows now
=> fix: bad newline getting sent on windows

.github/ISSUE_TEMPLATE/bug_report.yml
Make it more clear that we need the actual commands that people run
=> Improve bug report template

run.py
=> Separately save patch files + some typing cleanup

README.md, sweagent/agent/models.py
This is a fixup to #16. We shouldn't simply override the `--model_name` option from the CLI with something from `keys.cfg`
=> Remove azure override of model name

sweagent/environment/swe_env.py, tests/test_env.py
Closes #148 
Possible usages:
```bash
run.py .... --environment_setup=/path/to/script.sh
run.py .... --environment_setup=/path/to/script.yml
```
where in the last case, the yaml file takes the following form:
```yaml
install: echo 'installing'
packages: pytest
pip_packages: tox
python: '3.6'
```
=> Allow to supply installation commands when running on gh issues

run.py, sweagent/agent/agents.py, sweagent/agent/commands.py, sweagent/agent/models.py, sweagent/environment/swe_env.py
The docstrings of the argument dataclasses are also used in the --help
message. If they aren't set, the signature of the dataclass is shown
instead.
=> Improve --help message option headers

sweagent/environment/swe_env.py
=> Better error handling for --open_pr

run.py
I've ran into this error several times, where it says model_patch can't be None and ending the entire program.
=> Fixed a potential error

setup.sh
=> fix: TARGETARCH not set on some OS/docker setups

config/configs/default_sys-env_cursors_window100-detailed_cmd_format-full_history-1_demos.yaml, config/configs/default_sys-env_window100-detailed_cmd_format-full_history-1_demos.yaml, config/configs/xml_sys-env_cursors_window100-detailed_cmd_format-full_history-1_demos.yaml, config/configs/xml_sys-env_window100-detailed_cmd_format-full_history-1_demos.yaml, config/default.yaml, config/default_from_url.yaml
None
This update fixes all(5) occurrences of "doensn't" typo in config templates.
=> Fix typo - "doensn't" in templates

README.md
Fixes a tiny typo in the root README :')
You're doing amazing work.
=> fix: typo in root readme

sweagent/environment/utils.py
Closes #331
It's unlikely that job control was ever granted. Currently we're getting
ERROR    Unexpected container setup output: /bin/bash: cannot set terminal process group (-1): Inappropriate ioctl for device
/bin/bash: no job control in this shell
Because of this.
=> Fix: Do not request job control in bash

mkdocs.yml
Closes #387
Search is added by default but must be manually added if any other plugins are
configured
See https://github.com/squidfunk/mkdocs-material/blob/master/docs/setup/setting-up-site-search.md
=> Docs: Add search

sweagent/agent/agents.py
=> Print trajectory path only at beginning/end

sweagent/agent/models.py
=> Fix: IndexError when replaying incomplete trajectories

docs/usage/cl_tutorial.md, sweagent/environment/swe_env.py, tests/test_env.py
Follow up to #317 
- **Add test for caching of task envs**
- **Make cached image name depend only on relevant features**
=> Cached task instances (2)

docs/config/config.md, docs/config/env.md, mkdocs.yml, run.py, sweagent/__init__.py, sweagent/agent/agents.py, sweagent/agent/commands.py, sweagent/environment/swe_env.py, sweagent/utils/config.py, tests/test_replay.py, tests/test_utils.py
This PR should allow to run `run.py` from another directory. This is a preparation for making it available as a python package.
Closes #225
=> Resolve relative paths to demonstrations and commands

docs/faq.md, docs/usage/usage_faq.md, mkdocs.yml
I put it at the end rather than before reference. I think it's actually easier to find that way.
@ofirpress
=> Doc: Add FAQ

docs/faq.md, start_web_ui.sh
Fixes https://github.com/princeton-nlp/SWE-agent/issues/481
This PR moves the Flask server startup to first in the script, which gives it (slightly) more time to write to `web_api.log` in the case of quick failures (such as in the case of https://github.com/princeton-nlp/SWE-agent/issues/480).
Honestly, we could also just stuff a `sleep 2` in `print_log` before the `cat` call (that also works, but involves a delay to output), or ignore it altogether (there isn't much likelihood of failures this quick – I just played with all of this because of the above issue).
Compare the above issue's output to this PR:
```
(venv) stuart 0 SWE-agent fix-empty-log-results > ./start_web_ui.sh
up to date, audited 1820 packages in 2s
349 packages are looking for funding
run `npm fund` for details
8 …
```
=> Web UI: Start the Flask server first.

docs/faq.md, start_web_ui.sh
Fixes https://github.com/princeton-nlp/SWE-agent/issues/478
This PR uses the PID returned when starting the Flask server to later clean up those processes on exit. This can avoid having to clean up manually before running the `start_web_ui` script again, or having to handle alternate ports or existing processes.
1. Run `./start_web_ui.sh`, then exit out of it.
2. Use `lsof -i :8000` to verify there are no processes on that port.
=> Web UI: Kill the Flask server on exit.

sweagent/frontend/src/components/controls/LRunControl.js
Fixes https://github.com/princeton-nlp/SWE-agent/issues/483
It just keeps the console clean for when real problems come up. 🙃
| Before | After |
| --- | --- |
| <img width="1036" alt="Screenshot 2024-06-01 at 4 23 40 PM" src="https://github.com/princeton-nlp/SWE-agent/assets/349751/f4bd599d-8d54-4437-8fb4-0fb6195375ec"> | <img width="1036" alt="Screenshot 2024-06-01 at 4 35 06 PM" src="https://github.com/princeton-nlp/SWE-agent/assets/349751/9ba5c6a3-070e-4d73-aea1-f2727fb1539a"> |
1. Run `./start_web_ui.sh`.
2. Verify there are no warnings on the front-end in the console.
=> Web UI: Correct `class` usage.

sweagent/frontend/src/Run.js, sweagent/frontend/src/components/panels/AgentFeed.js, sweagent/frontend/src/components/panels/EnvFeed.js
Issue #328: 
- "Every time a new message appears in one of the feeds/logs of the web UI, we scroll to the bottom. However, if a user wants to read a certain part during the run and has scrolled up, we shouldn't scroll down."
Solution: 
- Implemented useRef's to track whether a user has scrolled in either EnvFeed, AgentFeed, or LogPanel. If a user has scrolled, at each update per feed/panel, do not auto-scroll. Otherwise, if a user has not scrolled or has scrolled to the bottom, at each update per feed/panel, continue to auto-scroll.
- Removed basic scrolldown feature from EnvFeed.js, AgentFeed.js, and Run.js for redundancy.
=> Issue #328: Auto-scrolling in web-UI Update

evaluation/aggregate_results.py, evaluation/evaluation.py, inspector/server.py, inspector/static.py, make_demos/convert_traj_to_demo.py, run_replay.py, sweagent/agent/agents.py, sweagent/agent/commands.py, sweagent/agent/models.py, sweagent/environment/swe_env.py, sweagent/environment/utils.py
Fixes #446 
Fixes issues identified by Ruff which advises on proper file handling in Python. Replaces direct file handling methods with safer context handler by using `Path.read_text()` and `with open(...) as file:` where appropriate. 
1. evaluation/aggregate_results.py
2. evaluation/evaluation.py
3. inspector/server.py
4. make_demos/convert_traj_to_demo.py
5. run_replay.py
6. sweagent/agent/agents.py
7. sweagent/agent/commands.py
8. sweagent/agent/models.py
9. sweagent/environment/swe_env.py
10. sweagent/environment/utils.py
11. inspector/static.py
=> Issue #446: Fixed calls to open without ctx manager

sweagent/frontend/src/components/AgentMessage.js
Fixes https://github.com/princeton-nlp/SWE-agent/issues/485
This PR uses the already-installed `react-markdown` package to render agent feed messages as markdown.
| Before | After |
| --- | --- |
| <img width="1235" alt="Screenshot 2024-06-01 at 5 03 48 PM" src="https://github.com/princeton-nlp/SWE-agent/assets/349751/a762566a-4ac0-4760-a047-8e17753b4d9b"> | <img width="1229" alt="Screenshot 2024-06-01 at 5 21 02 PM" src="https://github.com/princeton-nlp/SWE-agent/assets/349751/008b41e3-51b4-4e15-9b22-5d6d71d2de8b"> |
1. Run `./start_web_ui.sh`.
2. Set a problem source and click Run.
3. As content fills the agent feed (the "Thoughts" section), verify it's rendered as markdown, and not literally.
=> Web UI: Render Markdown in agent feed messages.

docker/swe.Dockerfile, setup.sh, sweagent/environment/swe_env.py, tests/test_env.py
Saves about 20s (out of 30s for setting up the conda env to begin with).
Currently only enabled for what's like the single issues (as opposed to the SWE-bench ones).
Todo:
Closes #491
=> Enh: Start from clone of python conda environment for speedup

sweagent/agent/models.py
…AzureOpenAI
Fixes #571 
Log warning message that model command line arg is ignored in case of using AzureOpenAI.
=> Fixed #571 - show message that model arg is ignored in case of using Azure OpenAI

sweagent/environment/swe_env.py, sweagent/environment/utils.py
Closes #595 
Fix: Process done marker not found in read with timeout
This happened when both stderr and stdout were written to.
There was no guarantee that the suffix that prints the exit status would
actually be last.
Fix:
* Add a bit of timeout
* Search in all lines rather than just the last one for the exit code
Either of these should reasonably fix this.
=> Fix: Process done marker not found in read with timeout

config/default_xml.yaml, sweagent/agent/models.py
Add claude 3.5 sonnet to models and add a default_xml config to configs to better support claude models
Fixes #600
Adds model name and cost details to `sweagent/agent/models.py`
Also adds the `default_xml.yaml` in configs, which is the preferred version to use with claude.
=> Add claude 3.5 sonnet to models

requirements.txt
Caps the `swebench` package dependency `<2.0.0` to avoid breaking changes in the major version update.
We should update SWE-agent to use the new `swebench` package in the near future, but this should avoid issues with new users of SWE-agent.
=> Cap swebench version dependency

tests/test_server.py
Fixes #357 by adding basic test for high coverage of `api/server.py`
**What does this implement/fix? Explain your changes.**
- Creates basic flask client
- Tests the creation of client
- Tests the `"/run"` route 
- Tests the `"/stop"` route
=> Issue #357: How to easily test flask API?

config/commands/filemap.py, docker/requirements.txt
n/a
Adds a "filemap" command to aid in exploring large files/codebase and avoid `scroll_down`-hell. For example,
```
$ filemap SWE-agent/sweagent/agent/agents.py
...
239 class Agent:
240     """Agent handles the behaviour of the model and how it interacts with the environment."""
241 
242     def __init__(self, name: str, args: AgentArguments):
243 ... eliding lines 243-256 ...
257 
258     def add_hook(self, hook: AgentHook):
259         """Add hook to agent"""
260         hook.on_init()
261         self.hooks.append(hook)
262 
263     def _append_history(self, item: dict):
264         for hook in self.hooks:
265             hook.on_query_message_added(**item)
266         self.history.append(item)
267 
268     def setup(self, instance_args, init_model_stats=None) -> None:
269 ... eliding …
```
=> Add filemap command in the spirit of repomap

config/commands/defaults.sh
This issues a warning if the model wants to scroll >= 3 times in a row.
=> Enh: Warn if scrolling >= 3 times

sweagent/agent/commands.py
SYSTEM message changes:
before: moves the window down {WINDOW} lines
after: moves the window down 100 lines
I was playing it and found that in special commands section in the system message, `{WINDOW}` was not replaced with the desired value of `100`. Dig into it a little bit and I believe this should fix it. Not sure if there would be side effects tho.
=> ensure variables work in special command docstring

config/commands/_split_string.py
Depending on the python version you otherwise get warnings when the tool is being used.
=> Avoid future import in tools

docs/usage/coding_challenges.md, sweagent/agent/models.py
NA
It looks like the current pricing figures for gpt-4o-mini are the same / copied from the pricing figures for gpt-4o. I believe they should be updated to reflect the OpenAI pricing page (5 per m input => .15 per m input, 15 per m output => .6 per m output)
Source: https://openai.com/api/pricing/
=> Update pricing numbers for gpt-4o-mini-2024-07-18

sweagent/agent/models.py
Fixes https://github.com/princeton-nlp/SWE-agent/issues/748
=> Fix: Submitting ' ' in human mode crashes container

sweagent/environment/utils.py
=> More helpful message if --repo_path doesn't exist

sweagent/environment/swe_env.py, tests/test_replay_ctf.py
=> Fix: 'NoneType' object has no attribute 'session_process'

inspector/static.py, run.py, sweagent/agent/agents.py, sweagent/agent/summarizer.py, sweagent/environment/swe_env.py
Closes #775 
Completed #775 : Add full tracebacks to all exception statements
Added full tracebacks to all exception statements
This change will improve our ability to diagnose issues related to setting environment variables and retrieving commit hashes, providing clearer insights into the root causes of failures.
\SWE-agent\run.py
\SWE-agent\sweagent\agent\agents.py
\SWE-agent\sweagent\agent\summarizer.py
\SWE-agent\sweagent\environment\swe_env.py
=> Improved logging by using traceback.format_exc() 

sweagent/frontend/src/components/controls/LRunControl.js
Fixes https://github.com/princeton-nlp/SWE-agent/issues/362
Use `useEffect` to monitor the problem source dropdown, and when it changes, reset the user value to empty (so that the default text appears for that field).
The textarea corresponding to the "Write" dropdown doesn't need changes since the actual markup is updated on switch (between `input`s and `textarea`).
1. On a fresh page load, enter something into the "GitHub issue URL" field.
2. Switch the dropdown above it to "Local file", and verify the "Path to local .MD..." field is empty (displaying the placeholder text).
3. Enter data in that field again, and switch the dropdown back to its original value. Verify the "GitHub issue URL" field is empty again.
=> Web UI: Reset the user-entered source value after changing the problem source dropdown.

sweagent/agent/agents.py, sweagent/agent/interactive_commands.py, sweagent/environment/swe_env.py, sweagent/environment/utils.py, tests/test_commands/_interactive_dummy.py, tests/test_commands/interactive_dummy_wrapper.sh, tests/test_data/config_files/dummy_interactive.yaml, tests/test_run.py
- **Typing fixes and docstrings**
- **Extract interactive command handling into InteractiveSession**
=> Improve testing of interactive commands

docs/config/commands.md, docs/config/demonstrations.md, docs/config/summarizers.md
Corrected minor phrasing issues in demonstration, summarizer, and command configuration docs for clarity.
- The phrase "Observation output exceeding these number, will be summarized" corrected to "Observation output exceeding this number will be summarized."
- "we only ingest demonstrations in the from of a trajectory file" corrected to "we only ingest demonstrations in the form of a trajectory file."
- "You can also leverage third party libraries (check out how we do linting enabled edit in config/commands/edit_linting.sh)" corrected to "You can also leverage third-party libraries (check out how we enable linting in config/commands/edit_linting.sh)."
=> Improved Clarity in Demonstration, Summarizer, and Command Configuration

tools/defaults/config.yaml
The default action "scroll_up" has inconsistent description, the same as for "scroll_down"
The proposed change fixes the spell in the description of the action
=> Fixed  the spell, that may mislead model

sweagent/__init__.py
Gives users guidance if they would otherwise hit:
```
╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Validation error                                                                                                  │
│                                                                                                                   │
│ The following errors are raised by Pydantic, trying to instantiate the configuration based on                     │
│ the merged configuration dictionary (see above).                                                                  │
│                                                                                                                   │
│ Every new indented block …
```
=> Enforce swe rex version lower bound

docs/usage/batch_mode.md, docs/usage/cl_tutorial.md, docs/usage/hello_world.md
Fixes #890 (it seems like the JS based approach didn't seem to work so lets get rid of the annotations)
=> Doc: Fix line endings for multi-line bash commands

pyproject.toml
Pin `textual` dependency as the inspector fails to start without textual and crashes if a version above 1.0.0 is installed. I'm observing this behavior with `uv` which presumably hides `textual` included by transitive deps (to repro: `uv venv -p 3.11` + `uv sync`, then `uv run sweagent ...`)
Error message without textual dependency.
```
$ sweagent i trajectories/demonstrations/replay__marshmallow-code__marshmallow-1867__default_sys-env_cursors_window100__t-0.20__p-0.95__c-2.00__install-1
👋 INFO     This is SWE-agent version 1.0.0 (7f74ae7390b8efd66e07913270c2738cc7e3bba9) with SWE-ReX 1.1.1 ().                                                                              
Traceback (most recent call last):
File <redacted>/.venv/bin/sweagent", line 10, in <module>
sys.exit(main())
^^^^^^ …
```
=> Pin textual to version 1.0.0

sweagent/agent/models.py
The current chat completions may include `tool_calls=None`, which trips up some OpenAI-compatible HTTP servers.
The `tool_calls` field is always present AFAICT, so this PR changes the logic to only set tool_calls when it's non-`None`.
None.
N/A.
=> OpenAI API: Don't pass None tool_calls to the OpenAI API

pyproject.toml, sweagent/__init__.py, sweagent/run/batch_instances.py
This PR depends on pending PR https://github.com/SWE-agent/SWE-ReX/pull/165
Fixes #893 
Fixes #936
For swe-bench batch instances, we set the platform to be linux/amd64 deterministically, which allows the `python_standalone_dir` to be built and set properly in swe-rex, enabling faster swe-bench batch runs on `amd64` arch machines.
> Note!
We'll need to update the dependencies to require a new swe-rex version, once https://github.com/SWE-agent/SWE-ReX/pull/165 is merged to swe-rex
=> Forces platform to be linux/amd64 for swe-bench batch runs

sweagent/inspector/fileViewer.js
Sometimes Trajectory viewer fails to load a file
and throws an error "TypeError: Cannot read properties of null (reading 'replace')". This is because there is a possibility for `item.action` to be `none`.
=> Fix "TypeError: Cannot read properties of null (reading 'replace')" in Trajectory viewer

sweagent/agent/models.py
Fixes #1038 
This Merge Request removes the hard check for specific model names. It changes the following lines:
```python
if tools.use_function_calling:
if not litellm.utils.supports_function_calling(model=self.config.name):
msg = (
f"Model {self.config.name} does not support function calling. If your model"
" does not support function calling, you can use `parse_function='thought_action'` instead. "
"See https://swe-agent.com/latest/faq/ for more information."
)
raise ModelConfigurationError(msg)
```
This current code does not allow for custom model names, which are (sadly) sometimes the case (e.g. `azure/4o-mini` would not work, because it's not in the list of LiteLLM models)
Because sometimes custom names / mappings are required, this change turns the Exception into a logger warning …
=> chore: Change function calling check Exception to only raising a warning

sweagent/run/run_batch.py
According to the changes in #1046 where the default trajectories directory is set here:
https://github.com/SWE-agent/SWE-agent/blob/71f2ed93d544b6fbd3b5d52792679579175fc881/sweagent/__init__.py#L46
It looks like it should be used here:
https://github.com/SWE-agent/SWE-agent/blob/71f2ed93d544b6fbd3b5d52792679579175fc881/sweagent/run/run_batch.py#L115
=> Use default trajectories dir according to ENV

sweagent/agent/agents.py, sweagent/tools/tools.py
=> Fix: fix Windows path error, replace Path with PurePosixPath or string

sweagent/run/common.py
The config help options were difficult to read because they weren't being printed with rich_print.
E.g.
```
> sweagent run --help_option sweagent.environment.swe_env.EnvironmentConfig
[green][bold]deployment[/bold][/green]: Deployment options.
This config item can be one of the following things (run [green]--help_option <name>[/green] for more info):
[green]swerex.deployment.config.LocalDeploymentConfig[/green]
[green]swerex.deployment.config.DockerDeploymentConfig[/green]
[green]swerex.deployment.config.ModalDeploymentConfig[/green]
[green]swerex.deployment.config.FargateDeploymentConfig[/green]
[green]swerex.deployment.config.RemoteDeploymentConfig[/green]
[green]swerex.deployment.config.DummyDeploymentConfig[/green]
[green][bold]repo[/bold][/green]: Repository options.
This config item …
```
=> Missing rich_print made help message difficult to read.

sweagent/tools/tools.py, tools/defaults/install.sh, tools/edit_anthropic/install.sh
Previously, if other toolbundles were specified, the state might not
have existed (we try and read it before we even execute the first
action)
In reference to #1048
=> Fix: Ensure state exists

docs/usage/hello_world.md
It's just a single character doc fix in the hello world doc
=> Fix spelling of 'agent' in hello world

docs/usage/cli.md, docs/usage/trajectories.md, sweagent/agent/agents.py, sweagent/inspector/fileViewer.js, sweagent/types.py
The query attribute now corresponds to the exact input for the LM at the current step.
Preciously, the messages attribute for step i was essentially the input for step i+1 in all but rare cases (requeries, etc.). The query attribute now supersedes the messages attribute.
=> BREAKING CHANGE: messages -> query field in traj

sweagent/run/hooks/open_pr.py
The commit message by the agent does not formatted properly
This pull request includes a small change to the `open_pr` function in `sweagent/run/hooks/open_pr.py`. The change updates the string formatting for commit messages to use f-strings for formating the message properly
=> Fix: Correctly format commit message for PR creation

tools/edit_anthropic/install.sh
=> Fix: Ignore missing treesitter for very old python

sweagent/tools/parsing.py
The `XMLFunctionCallingParser` is striping arguments from the models when converting to tool call, which can lead into issues when using old_str/new_str tools, as the fields would be modified. 
For instance, if the model wants to replace \n   a, that would actually be seen as a. 
This PR uses re.sub(r"^\n|\n$", "", text) removes at most one newline at begging and end of the field, such that 
```
<parameter=example_parameter_2>
This is the value for the second parameter
that can span
multiple lines
</parameter>
</function>
```
gives as param 
```
This is the value for the second parameter
that can span
multiple lines
```
=> Fixes #1166: strip incorrect for XML function calling

tests/tools/test_default_utils.py, tools/windowed/lib/windowed_file.py
WindowedFile never displays the last line of a file if the total number of lines exceeds the `WINDOW` size.
The bug originates from the `first_line` setter  in `tools/windowed/lib/windowed_file.py`:
```python
self._first_line = max(0, min(value, self.n_lines - 1 - self.window))
```
The maximum possible value for `first_line` is `self.n_lines - 1 - self.window`, which is too small by 1. 
Consider a 200-line file with a 100-line window size. The maximum possible value of `first_line` is 200 - 1 - 100 = 99. This corresponds to the window 99:198, meaning that line 199 is never displayed.
This PR fixes the bug by removing the `- 1` in the `first_line` setter:
```python
self._first_line = max(0, min(value, self.n_lines - self.window))
```
It also makes minor additions to …
=> Fix: WindowedFile bug preventing last line of a file from being displayed

docs/installation/changelog.md, docs/installation/codespaces.md, docs/installation/source.md
This PR fixes malformed markdown links throughout the changelog documentation in \`docs/installation/changelog.md\`. The issue was with nested brackets causing incorrect link formatting like `[#787]([#787](url))` instead of the correct `[#787](url)` format.
**Changes made:**
- Fixed malformed markdown links in all release sections (0.8.0, 0.7.0, 0.6.1, 0.6.0, 0.5.0, 0.4.0)
- Corrected PR reference links to use proper markdown syntax
- Ensured all GitHub PR links are properly formatted and clickable
The fix improves documentation readability and ensures all PR references are properly linked to their corresponding GitHub pull requests.
=> Docs: Fix malformed markdown links in installation documentation

docs/dev/contribute.md, docs/dev/formatting_conflicts.md
This PR fixes typos and URL corrections in the developer documentation:
**Files modified:**
- `docs/dev/contribute.md` - Fixed typo "easy-tow-rite" → "easy-to-write" and updated ruff GitHub URL from old repository to current one
- `docs/dev/formatting_conflicts.md` - Fixed typo "upstream/mean" → "upstream/main" and corrected git branch command parameter order
**Changes:**
- Updated ruff repository URL from `charliermarsh/ruff` to `astral-sh/ruff` (the project moved organizations)
- Fixed typo in test writing guidance: "easy-tow-rite" → "easy-to-write"
- Corrected git branch creation command parameter order
- Fixed reference to upstream branch from "mean" to "main"
These are documentation quality improvements that enhance readability and ensure accurate instructions for contributors
=> Doc: Fix typos and URL corrections in developer documentation

.github/workflows/check-links-periodic.yaml, docs/usage/batch_mode.md, docs/usage/coding_challenges.md, mlc_config.json
Having a `/` after the filename in the anchor link of a markdown is not widely supported. Though these links were properly navigating in the GitHub web interface, they weren't when I tried in VSCode preview window. But removing the `/` made it work both places. Also, it fixes the errors reported by `markdown-link-check` GitHub Action.
The leetcode url was redirecting to a sub-route. Probably the link-checker isn't following redirections. So, replaced with the target url of the redirection.
=> Fix broken references in markdown files

docs/config/environments.md
N/A 
This pull request fixes an incorrect command-line argument in the documentation.
When running the example command, using `--env.image` results in a `RuntimeError: Invalid command line arguments.`. This can be confusing for new users trying to get started with `swe-agent`.
My change corrects the argument to `--env.deployment.image`, which is the valid argument and allows the command to execute successfully.
**Files Modified:**
*   `docs/config/environments.md`
This small fix improves the user experience by ensuring the provided examples work.
=> Docs: Fix invalid argument `--env.image` in command example

.devcontainer/devcontainer.json
Fixes #1272
The docker-in-docker extension used in dev containers seems to be old, which causes a failure on extension installation, and then you can't use the dev environment. I am using the config alternative posted in https://github.com/devcontainers/features/tree/main/src/docker-in-docker.
This makes the dev container able to start
=> fix: update docker-in-docker feature reference in devcontainer

sweagent/environment/repo.py
Fixes https://github.com/SWE-bench/SWE-smith/issues/141
Unlike SWE-bench style instances, where the a task instance's starting state for a codebase is configured by checking out a base commit at some prior point in the repository, in SWE-smith the bugs are stored are branches. However, the existing `git reset --hard {base_commit}` doesn't work for checking out a branch.
This PR makes a minor change to the setup script commands that adds an explicit `git checkout` which should work for both branches and past commits.
=> Add explicit `checkout` step

sweagent/run/batch_instances.py, tests/test_batch_instance.py
Fixes https://github.com/SWE-agent/SWE-agent/issues/1290
I edited every image name that was not specific enough with adding `docker.io/` prefix. It should now work with podman.
=> use docker.io prefix to pull image (for podman)
