sweagent/environment/swe_env.py

More helpful error message if docker is not running

---

sweagent/agent/history_processors.py

Fix typo omitted

---

run_replay.py

config_file is a required arg in run_replay.sh

---

sweagent/agent/models.py

Handle with missing prompt_eval_count in Ollama

---

run_replay.py

Fix: Allow run_replay with github URLs as data_path

---

sweagent/environment/swe_env.py
sweagent/environment/utils.py

Invalid image names stopped us from using images pulled from dockerhub

Fix: Using docker images from dockerhub

---

README.md

Add run via docker instructions to readme

---

run.py

Closes #97 
Closes #100
Closes #96

Fix: Update default image name

---

run.py
run_replay.py

I want to be able to use a debugger to solve issues with the scripts. This only works if we raise exceptions.
- **Add flag to raise exceptions in run.py** instead of entering retry loop
- **Forward unparsed arguments in run_replay.py to run.py**
- **Fix: Unbound local variable/name shadowing**
- **Do not leave python when calling run.py** but rather simply pass arguments

Improve ease of debugging

---

README.md
setup.py
sweagent/agent/models.py

add npx and openapi base url and model name keys - resolves #64

---

sweagent/agent/models.py

Fix: Choosing TogetherAI models

---

inspector/server.py

seperately -> separatelyied for this fix.

Fix typo in server.py

---

docker/getconda.sh
docker/swe.Dockerfile
release_dockerhub.sh
setup.sh

- **Select the right conda path from within the container**
- **Build multiplatform images**

multiplatform docker builds

---

sweagent/environment/utils.py

Closes #114
Closes #123
Closes #159

Improve error handling of docker issues

---

run.py
sweagent/agent/models.py

- refactor codes for clearness

refactor: Simple refactoring for clean code

---

README.md
run.py
sweagent/environment/swe_env.py

Make github token fully optional

---

run.py

nit: typos

---

README.md

docker pull will auto select platform . in mostly time we don't need to specific the platform.

update doc of docker pull image

---

run.py

improve patch print message

---

tests/test_parsing.py

Fixes #186
Write simple unit tests.
- It should work when given a string in the expected format.
- It should raise an exception when given a string in an unexpected format.

test: add tests for parsing functions

---

run.py
sweagent/environment/swe_env.py

This addresses a bug when using `--open_pr` with `--repo_path` (previously `--push_gh_repo_url`).

Fix opening PR from fork

---

sweagent/environment/swe_env.py
sweagent/environment/utils.py
tests/conftest.py
tests/test_env.py

Tests to use fast experimental communication strategy

---

tests/test_env.py

Speed up testing with persistent containers & remove them end of session

---

environment.yml
run.py
setup.py

Add usage doc to run.py

---

sweagent/agent/models.py

None
Adds `gpt-4-turbo-2024-04-09` and a corresponding shortcut `gpt4-turbo`.
This appears to work for me when I've tested it locally

Add GPT4-turbo model

---

config/configs/default_sys-env_cursors_window100-detailed_cmd_format-full_history-1_demos.yaml
config/configs/default_sys-env_window100-detailed_cmd_format-full_history-1_demos.yaml
config/configs/xml_sys-env_cursors_window100-detailed_cmd_format-full_history-1_demos.yaml
config/configs/xml_sys-env_window100-detailed_cmd_format-full_history-1_demos.yaml
config/default.yaml
config/default_from_url.yaml

None
This update fixes all(6) occurrences of "succesfully" typos in config templates.

Fix typo - "succesfully"

---

run.py
sweagent/agent/models.py
sweagent/environment/swe_env.py
sweagent/environment/utils.py
tests/conftest.py
tests/test_run.py

Refactor run.py main function into class with hook structure

---

sweagent/agent/agents.py
sweagent/agent/models.py
tests/test_run.py

Adds hooks to the `Agents` class that are going to be used for the web server. Prototype will be in #240

Add hooks to agent

---

config/configs/default_sys-env_cursors_window100-detailed_cmd_format-last_5_history-1_demos.yaml
config/configs/default_sys-env_window100-detailed_cmd_format-last_5_history-1_demos.yaml
config/configs/xml_sys-env_cursors_window100-detailed_cmd_format-last_5_history-1_demos.yaml
config/configs/xml_sys-env_window100-detailed_cmd_format-last_5_history-1_demos.yaml
config/default_from_url.yaml
sweagent/__init__.py
sweagent/agent/agents.py
sweagent/agent/models.py
sweagent/environment/swe_env.py
sweagent/environment/utils.py
sweagent/web/server.py
sweagent/web/static/scripts/mainscript.js
sweagent/web/static/styles/mainpage.css
sweagent/web/templates/index.html
tests/conftest.py
tests/test_env.py

> [!NOTE]
> This is just a test. Leaving this here in case people want to try something similar, but it's not meant to be merged like this.

Run swe-agent from a flask server

---

sweagent/environment/swe_env.py

This ensures that the `environment.yml` is correctly constructed with the specific Python version required for the instance.
Fixes #270 
This ensures that the correct Python version is selected in the case that the instance's conda environment is being created using the `--file` variants.

Pass Python version to get_environment_yml

---

environment.yml
sweagent/agent/models.py
tests/test_models.py

Fixes #135
I fixed the incompatibilities caused by the major version update of Together.
- update the code to align with the new API request format
- specify the Together version to the latest in environment.yml
- create unit test

Fix Together model validation error

---

.devcontainer/README.md
.devcontainer/devcontainer.json
.devcontainer/oncreate.sh
.devcontainer/sample_keys.cfg
README.md

- **Codespaces: Remove shell setting; fix extensions setting**
- **Codespaces: Copy sample keys.cfg**
- **Codespaces: Add codespace badge**

Improve codespace setup & documentation

---

.dockerignore
.gitignore

Fix: Include demonstrations in dockerignore

---

.pre-commit-config.yaml
README.md
config/commands/README.md
inspector/server.py
make_demos/convert_traj_to_demo.py
pyproject.toml
sweagent/environment/utils.py
tests/test_data/trajectories/gpt4__klieret__swe-agent-test-repo__default_from_url__t-0.00__p-0.95__c-3.00__install-1/args.yaml
tests/test_data/trajectories/gpt4__swe-agent-test-repo__default_from_url__t-0.00__p-0.95__c-3.00__install-1/args.yaml
tests/test_data/trajectories/gpt4__swe-bench-dev-easy_first_only__default__t-0.00__p-0.95__c-3.00__install-1/args.yaml
tests/test_models.py
tests/test_replay.py

reaction to #19 #45 #55 #133 #155 #212 #254 #255
adding typo check as pre-commit hook
cc: @klieret

lint: use `typos` as precommit's hook

---

README.md

Doc: Recommend pip install instead of conda

---

sweagent/environment/swe_env.py

fix typo. no functional change

fix typo in swe_env.py

---

sweagent/api/server.py
sweagent/frontend/src/components/controls/LRunControl.js

Web: Fix script_path input

---

inspector/server.py
run.py

Fix: Don't print patch msg for exit_cost patch

---

sweagent/agent/models.py

This adds support for OpenAI's gpt-4o model, released today, which is faster that gpt-4-turbo at half the [price](https://openai.com/api/pricing/). We do not yet know the affect on benchmark scores but I was able to run this example case successfully:
```
python run.py --model_name gpt4o --data_path https://github.com/pvlib/pvlib-python/issues/1603 --config_file config/default_from_url.yaml
```

Add gpt-4o model

---

sweagent/api/server.py
sweagent/environment/utils.py
sweagent/frontend/src/Run.js
sweagent/frontend/src/components/controls/LRunControl.js

Web: Allow to specify commit hash

---

.github/workflows/pytest.yaml

CI: Use uv pip install

---

sweagent/api/hooks.py
sweagent/api/server.py
sweagent/frontend/src/Run.js

Web: Shorten long error messages in banner

---

sweagent/environment/utils.py

Wait longer if processes still running

---

inspector/fileViewer.js

Inspector: Better labels for roles

---

inspector/fileViewer.js
inspector/static.py
inspector/style.css

Change icons for trajectory viewer

---

.github/workflows/pytest.yaml
.github/workflows/test_build_containers.yaml
mkdocs.yml

- **Docs: Add github button; edit feature**
- **Docs: Change color preferences**
- **Docs: Add next prev/buttons**
- **CI: Skip CI for PRs that only touch docs**

docs improvements

---

requirements.txt

Exclude requests version that causes docker issues

---

config/README.md
config/commands/README.md
inspector/README.md
trajectories/README.md

Doc: Replace symlinks with markdown files with links

---

CODE_OF_CONDUCT.md

Docs: Add code of conduct

---

docs/installation/tips.md

Docs: Note about old images from the hub

---

requirements.txt

Remove requests upper bound, add docker-py lower bound

---

sweagent/environment/swe_env.py

- action is declared but never being used. Deprecate action argument from get_sumission

deprecate action from get_submission

---

docs/CONTRIBUTING.md
docs/dev/contribute.md
pyproject.toml

- **wip**
- **Docs: Add dev notes**

add dev notes

---

sweagent/agent/models.py

Enh: Suppress openai logging; improve formatting of stats

---

docs/installation/docker.md
docs/installation/keys.md
sweagent/__init__.py
sweagent/agent/models.py
sweagent/environment/swe_env.py
sweagent/utils/config.py
tests/test_models.py

Closes #188 
Closes #305 
Closes #111

Use custom Config class to support env and keys.cfg

---

docs/dev/contribute.md
evaluation/aggregate_results.py
evaluation/evaluation.py
inspector/server.py
inspector/static.py
make_demos/convert_traj_to_demo.py
pyproject.toml
run.py
run_replay.py
sweagent/agent/agents.py
sweagent/agent/commands.py
sweagent/agent/history_processors.py
sweagent/agent/models.py
sweagent/agent/parsing.py
sweagent/api/server.py
sweagent/api/utils.py
sweagent/environment/swe_env.py
sweagent/environment/utils.py
sweagent/utils/config.py
tests/conftest.py
tests/test_env.py
tests/test_env_utils.py
tests/test_models.py
tests/test_replay.py
tests/test_run.py

- **Add flake8-errmsg to tests**
- **Some more ruff checks**

More ruff checks

---

.github/PULL_REQUEST_TEMPLATE.md
docs/dev/contribute.md

Doc: Add notes about merge-conflicts after formatting changes

---

run.py
sweagent/agent/models.py
sweagent/environment/swe_env.py

Doc: Document keywords of run.py

---

CHANGELOG.md
docs/background/index.md
docs/background/overview.md
docs/index.md
docs/installation/index.md
mkdocs.yml

- **Docs: Improve navigation from front page**
- **Docs: Improve landing page**

Improve landing page and add background section

---

sweagent/environment/swe_env.py

Closes https://github.com/princeton-nlp/SWE-agent/issues/451

Ensure container_name is reset for non-persistent containers

---

sweagent/agent/agents.py
sweagent/environment/swe_env.py
sweagent/environment/utils.py

- **Change run return_type default to "info_trajectory"; doc improvements**
- **Doc: Ensure that all public methods have docstring stub**
- **Doc: Add SWEEnv docstrings**

add swe env docstrings

---

start_web_ui.sh

Fix: Remove -n option to wait

---

README.md

Update README.md - add link to faq

---

README.md

Doc: Bring back gh codespaces button to readme

---

docs/installation/codespaces.md
docs/installation/docker.md
docs/usage/web_ui.md
sweagent/api/index.html
sweagent/api/server.py

- **Fix: Show dummy page for flask backend**
- **Update docs**
Closes #490

add blank landing page 8000

---

docs/config/env.md
docs/usage/cl_tutorial.md
sweagent/environment/swe_env.py
tests/conftest.py

- **Ref: Refactor git clone command**
- **Feat: Support sparse clones**
Closes #227

Feat: experimental fast cloning

---

README.md

Update README.md - move citation to end of document

---

README.md

Removing figures to make the 5 sec demo more prominent. I've discussed this with John.
> [!NOTE]

Update README.md - remove bar plot and other fig

---

sweagent/frontend/package.json

Closes #449
https://stackoverflow.com/a/63231052/ (use 127...)
https://stackoverflow.com/a/57532447/ (trailing slash)

Fix: Try to avoid proxy errors

---

sweagent/environment/swe_env.py

Add timing information to SWEEnv

---

sweagent/environment/swe_env.py
tests/test_env.py

Fix: Repo cloned to wrong folder

---

sweagent/environment/swe_env.py
sweagent/environment/utils.py

- **Improve error handling**
- **Better error handling for pausing/terminating container**
- **env utils: improved typing and docs**

Improve docker container error handling

---

sweagent/environment/swe_env.py

Wait longer times for docker container to start if necessary

---

README.md

Update README.md - small readability improvements

---

run_replay.py

Fix: --traj_path is required

---

docs/config/demonstrations.md

Docs: Reorder demonstration section

---

start_web_ui.sh
sweagent/api/index.html

Enh: Point to documentation

---

sweagent/agent/agents.py

Enh: Remove redundant 'saved traj to X' messages

---

run.py
tests/test_run.py

Allow to disable config dump to log

---

docs/config/env.md
docs/usage/cl_tutorial.md
sweagent/api/server.py
sweagent/environment/swe_env.py
sweagent/utils/config.py
tests/conftest.py
tests/test_env.py
tests/test_run.py
tests/test_utils.py

Switch to fast communicate and sparse clone by default

---

sweagent/environment/utils.py

Change: Only wait 1s for docker to start

---

docs/usage/cl_tutorial.md
sweagent/environment/swe_env.py

Doc: Contrast persistent containers and cached task images

---

sweagent/environment/swe_env.py
tests/test_env.py

Fix: Do not allow persistent container with cache task imgs

---

config/environment_setup/py310_default.yaml
docs/installation/source.md
docs/usage/cl_tutorial.md
tests/test_env.py

Enh: Use uv for editable install by default

---

.github/workflows/release-dockerhub-release.yaml

CI fix: Strip leading v for version number

---

run.py
sweagent/agent/agents.py
sweagent/agent/models.py
sweagent/environment/swe_env.py
sweagent/environment/utils.py
sweagent/utils/config.py
sweagent/utils/log.py

- **Ref: SWEEnv logger access**
- **Ref: Factor out get_logger; fix access to sweenv log**

Factor out get_logger; fix access to sweenv log

---

docs/config/demonstrations.md

Update demonstrations.md - mentioning human_thought option

---

docs/config/commands.md
docs/usage/cl_tutorial_cmd_1_output.log
mkdocs.yml
sweagent/agent/agents.py

CI: Ensure that snippets are found

---

run.py
sweagent/utils/log.py

Enh: Always write log to traj directory

---

sweagent/environment/swe_env.py

Fix: Refresh container_obj before querying status

---

config/commands/_split_string.py
config/commands/edit_linting.sh
tests/test_commands.py

Fix: Linting blocks for existing lint errors

---

docs/usage/usage_faq.md

> [!NOTE]
In sweagent/agent/models.py, claude-3.5-sonnet is implemented, but the documentation for usage doesn't yet reflect that.

Doc: Update usage_faq.md to include the claude-sonnet-3.5 shortcut

---

CHANGELOG.md

Update CHANGELOG.md - fix typo

---

docs/config/env.md
sweagent/environment/swe_env.py
sweagent/utils/log.py

Make log level configurable; add TRACE level

---

run.py

Fix: Handle empty traj in should_skip

---

sweagent/environment/swe_env.py

This fixes two issues
1. Because of the sleep command, the exit status was always 0
2. If you typed `python` or some other rare commands, something would
crash and the variables in the last echo would not be evaluated.
This is now handled as a special case
Closes #630
Closes #642

Fix for end-marker communicate: Exit status always 0/invalid

---

sweagent/environment/swe_env.py

Fix: Insufficient quoting of git commit message

---

mkdocs.yml

Update mkdocs.yml - spell out ACI fully

---

config/coding_challenge.yaml

Update coding_challenge.yaml - small wording change

---

.gitignore
docs/usage/usage_faq.md
sweagent/agent/models.py

Fixes #637 
In this PR, I implemented the changes suggested in issue #637, which involves adding support for DeepSeek Coder as a model option in SWE-agent. The following modifications were made:
1. Model Integration: Added DeepSeek Coder to the list of selectable models in SWE-agent.
2. I included two minor changes to enhance the development workflow:
- ~~Added a justfile: This file includes helpful commands for starting the server, frontend, and switching between DeepSeek and OpenAI APIs.~~ _(EDIT: I reverted back this change. justfile was not introduced in this PR)_ 
- Updated .gitignore: Simplified the switch between preconfigured keys*.cfg files by modifying the pattern to ignore all keys*.cfg files instead of just keys.cfg.
I tested these changes and it seems that DeepSeek Coder …

feat: support deepseek-coder LLM

---

docs/config/env.md
sweagent/environment/swe_env.py
sweagent/environment/utils.py

Enh: Make timeout for agent commands configurable

---

docker/eval.Dockerfile
release_dockerhub.sh
setup.sh

No need to build eval docker container anymore

---

sweagent/utils/log.py

File handler is set to TRACE by default

---

sweagent/agent/agents.py

Important fix: Catch CostLimitExceeded in retry because of format/block

---

.github/workflows/release-dockerhub-nightly.yaml

CI: Do not try to run release script from fork

---

config/commands/_split_string.py
config/commands/filemap.py
pyproject.toml

Remove __future__ imports from commands

---

sweagent/environment/swe_env.py

Fix: sweunexpected keyword 'python_version'

---

sweagent/environment/swe_env.py

Fix: Use LONG_TIMEOUT for pre_install commands

---

docs/usage/coding_challenges.md

Update coding_challenges.md - add git init command

---

docs/usage/coding_challenges.md

Update coding_challenges.md - link to demos

---

docs/usage/benchmarking.md

Doc: Note about different default splits

---

run.py

Also create empty patch files for completeness

---

sweagent/agent/models.py

Thanks to @talorabr for the report

Fix: Raise ContextWindowExceeded instead of exit_cost

---

sweagent/environment/utils.py

Closes #728 
In reviewing the source code, I've found what appears to be some duplicate code.

removing duplicate code

---

sweagent/environment/utils.py

Fix: Deal with non-utf8 encoded bytes in comm

---

sweagent/__init__.py

Remove irrelevant log messages from datasets etc.

---

sweagent/agent/agents.py

Fix: Block su as command

---

tests/test_env_utils.py

CI: Use GITHUB_TOKEN from keys.cfg

---

.github/workflows/pytest.yaml
tests/test_replay_ctf.py

CI: Add network interface; tighten testing for enigma

---

config/commands/decompile.py
config/commands/disassemble.py
sweagent/agent/agents.py

Catch json decode errors

---

README.md

Update README.md - add citation

---

sweagent/agent/models.py

Add o1[-mini] support

---

.devcontainer/bashrc_epilog.sh

Fixes #352 
Removes a invalid char from the script

Fix: Remove invalid char from bashrc

---

docs/background/index.md

Update index.md - enigma

---

docs/index.md

Update index.md - ordering of buttons

---

inspector/server.py
pyproject.toml
run_replay.py
sweagent/agent/models.py
sweagent/environment/utils.py

Fixes #445
Removed all instances of os.path and used pathlib

Chore: Replace os.path with pathlib and update ruff lint rules

---

README.md

Update README.md - engima link

---

sweagent/agent/models.py

Fix: Correctly catch context limit exceeded error in openai

---

SECURITY.md

Doc: Security policy

---

.github/workflows/pytest.yaml
Dockerfile
pyproject.toml

The python versions to run SWE-agent in the repo aren't consistent. 
It_ would be good to align them.

Enh: Align supported python versions

---

docs/config/tools.md
docs/reference/bundle_config.md
mkdocs.yml

Doc: Add tool bundle config help

---

docs/installation/migration.md
docs/usage/inspector.md

Doc: Document new command line inspector

---

docs/reference/agent.md
docs/reference/agent_config.md
pyproject.toml
sweagent/agent/agents.py
sweagent/agent/models.py
sweagent/agent/reviewer.py
sweagent/environment/swe_env.py
sweagent/exceptions.py
sweagent/run/_progress.py
sweagent/run/batch_instances.py
sweagent/run/compare_runs.py
sweagent/run/merge_predictions.py
sweagent/run/remove_unfinished.py
sweagent/run/run.py
sweagent/run/run_batch.py
sweagent/tools/tools.py
sweagent/utils/log.py
tools/diff_state/bin/_state_diff_state

This PR introduces a lot of the features we've been using to make SWE-agent SOTA on SWE-Bench lite

SWE-agent 1.0 performance boosts: Retry & review and more

---

docs/installation/keys.md
sweagent/agent/models.py

Fix: Handling local models cost lookup issues

---

pyproject.toml

Thanks to @talorabr for spotting this!

Fix: Requires-python >= 3.11

---

pyproject.toml

CI: Temporarily downgrade griffe_pydantic

---

sweagent/run/inspector_cli.py

- **Ref: Var renames**
- **Fix: Reset step count when changing trajs**

traj inspector viewport reset

---

sweagent/agent/agents.py

Fix: Disable highlighting of model outputs

---

docs/config/models.md
docs/installation/keys.md

Doc: o1, prompt caching

---

sweagent/run/hooks/open_pr.py
tests/test_run_hooks.py

Fix: Create PRs

---

pyproject.toml

Unpin griffe pydantic

---

docs/config/models.md
docs/reference/history_processor_config.md
sweagent/agent/history_processors.py

Doc: Anthropic, cache control and more

---

sweagent/environment/swe_env.py

Enh: Set timeout for post_startup_commands

---

docs/config/config.md
docs/installation/keys.md
sweagent/tools/parsing.py

Doc fix: Specifying parsers

---

docs/installation/keys.md
sweagent/agent/models.py

Enh: Allow to override max_input_tokens for local models

---

sweagent/utils/log.py

Fix: Race condition/size change during iteration

---

sweagent/agent/agents.py
sweagent/run/run_batch.py

Fix: Handle total cost limit exceeded

---

sweagent/agent/models.py

Fix: Setting max_input_tokens to 0

---

sweagent/utils/log.py

Fix: Explicitly set log file encoding

---

sweagent/run/run_batch.py
sweagent/run/run_replay.py
sweagent/run/run_single.py

Fix: Ensure pydantic-settings env prefix set

---

sweagent/run/batch_instances.py

The current version is unable to run batch executions on modal because Docker seems to be the default environment. This PR fixes that. Not sure if I am missing something though.
#1022

run batch processing with modal

---

sweagent/agent/agents.py
tools/forfeit/bin/exit_forfeit

Fix: Catch exit forfeit

---

sweagent/environment/repo.py
sweagent/environment/swe_env.py

Ref: Get reset commands from repo

---

sweagent/agent/models.py

Fix: Show tenacity retry reasons

---

pyproject.toml
sweagent/run/inspector_cli.py

Fix: Compatibility with textual 2.0

---

sweagent/agent/models.py

Feat: Config/override max_output_tokens

---

sweagent/run/run_batch.py

- Added try-except block to handle JSON parsing errors when checking existing trajectories.
- Logs an error message and removes the trajectory if parsing fails.
Resolves: #1042

[#1042] fix(run_batch): handle JSON parsing errors in trajectory check

---

docs/config/env.md
sweagent/__init__.py

Enh: Allow to override tools dirs etc.

---

docs/usage/batch_mode.md
pyproject.toml

Doc: Document json/jsonl format

---

sweagent/tools/tools.py
tools/defaults/install.sh
tools/registry/install.sh

Fix: Ensure tools PATH takes precedence

---

.github/workflows/pytest.yaml

This PR sets up Codecov [Test Analytics](https://docs.codecov.com/docs/test-analytics), which enhances this project's existing Codecov coverage PR notification with details about failing, flaky, and slow tests. More details can be found [here](https://about.codecov.io/blog/find-failing-and-flaky-tests-with-codecov-test-analytics/), and below is an example screenshot.
1. Updated test run command to include --junitxml=test-results.xml so Codecov can parse test analytics.
2. Added codecov/test-results-action@v1 step to upload the generated test-results.xml for Test Analytics.
Looking forward to your feedback!

add test analytics

---

.cursor/rules/project-overview.mdc
sweagent/inspector/fileViewer.js

Fix: Inspector needs to handle new message format

---

sweagent/environment/swe_env.py

Enh: Change env emoji so it shows up

---

sweagent/run/hooks/open_pr.py

Fix: Token limit exceeded for PR body issue

---

sweagent/agent/models.py

Without special flags it can only do 64k

Fix: Work around litellm claude 3.7 tokens to 128k

---

sweagent/agent/agents.py

- **Fix: Updating total_execution_time after CommandTimeoutError**
- **Fix: max n consecutive timeout**

Fix execution time timeouts

---

sweagent/agent/agents.py
sweagent/agent/history_processors.py

- **Fix: Missing message_type field in requery**
- **Enh: Defensive: allow missing message_type**

fix message type missing

---

sweagent/tools/parsing.py

Fix: Handle non-string values in tool call

---

config/README.md
config/sweagent_0_7/07_thought_action.yaml
config/sweagent_0_7/07_thought_action_xml.yaml

Thanks @justinchiu-cohere
Closes #1171

Fix legacy configs (missing registry bundle)

---

sweagent/agent/agents.py

Config: Helpful feedback for timeouts

---

config/coding_challenge.yaml
config/default.yaml
config/default_backticks.yaml
config/demo/default.yaml
config/demo/no_instructions.yaml
config/demo/only_bash.yaml
config/exotic/default_shell.yaml
config/exotic/windowed_replace.yaml
config/exotic/windowed_replace_late_repro.yaml
config/human/human.yaml
config/human/human_demo.yaml
sweagent/tools/tools.py

Config: Disable pagers by default

---

docs/index.md
docs/usage/adding_custom_tools.md
mkdocs.yml
mlc_config.json

Doc: Add tutorial on adding new tools

---

config/README.md
docs/config/tools.md
docs/faq.md
docs/usage/adding_custom_tools.md

- **Doc: Improve FAQ organization**
- **Doc: Improve tool doc interlinking**

Doc improvements

---

docs/installation/codespaces.md

Doc: Remove mention of web UI
